name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling
  - pyarrow=2.0
  - ipywidgets
  - pip:
      - wandb==0.10.31
      - jinja2
